version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: favourite_films
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d favourite_films"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: movie_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: favourite_films
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "alembic upgrade head && python main.py"
    restart: unless-stopped

volumes:
  postgres_data: