"""initial

Revision ID: 0b90b3163ee7
Revises: c027e1025895
Create Date: 2025-05-08 13:43:22.939776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b90b3163ee7'
down_revision: Union[str, None] = 'c027e1025895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(length=20), nullable=False),
    sa.Column('movie_title', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'imdb_id', name='_user_movie_review_uc')
    )
    op.drop_constraint('favourites_user_id_fkey', 'favourites', type_='foreignkey')
    op.create_foreign_key(None, 'favourites', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favourites', schema='public', type_='foreignkey')
    op.create_foreign_key('favourites_user_id_fkey', 'favourites', 'users', ['user_id'], ['id'])
    op.drop_table('reviews')
    # ### end Alembic commands ###
