"""unique_usernames

Revision ID: fffffe9d4e58
Revises: d5787f38925e
Create Date: 2025-05-07 23:25:25.518910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fffffe9d4e58'
down_revision: Union[str, None] = 'd5787f38925e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favourites_user_id_fkey', 'favourites', type_='foreignkey')
    op.create_foreign_key(None, 'favourites', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_unique_constraint(None, 'users', ['username'], schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='unique')
    op.drop_constraint(None, 'favourites', schema='public', type_='foreignkey')
    op.create_foreign_key('favourites_user_id_fkey', 'favourites', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
